// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/generator.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateRequest defines the configuration for a generation job.
type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selection of the data schema to be used for generation.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*GenerateRequest_SchemaId
	//	*GenerateRequest_InlineSchema
	Source isGenerateRequest_Source `protobuf_oneof:"source"`
	// Total number of records to be generated. Supports massive volumes.
	Count uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// Seed for the pseudo-random number generator.
	// Use the same seed with the same schema to achieve deterministic output.
	Seed          uint32 `protobuf:"varint,4,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_api_proto_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetSource() isGenerateRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *GenerateRequest) GetSchemaId() string {
	if x != nil {
		if x, ok := x.Source.(*GenerateRequest_SchemaId); ok {
			return x.SchemaId
		}
	}
	return ""
}

func (x *GenerateRequest) GetInlineSchema() *Schema {
	if x != nil {
		if x, ok := x.Source.(*GenerateRequest_InlineSchema); ok {
			return x.InlineSchema
		}
	}
	return nil
}

func (x *GenerateRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GenerateRequest) GetSeed() uint32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type isGenerateRequest_Source interface {
	isGenerateRequest_Source()
}

type GenerateRequest_SchemaId struct {
	// Reference to a previously persisted schema ID in the database.
	SchemaId string `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3,oneof"`
}

type GenerateRequest_InlineSchema struct {
	// Ad-hoc schema definition for immediate use without prior persistence.
	InlineSchema *Schema `protobuf:"bytes,2,opt,name=inline_schema,json=inlineSchema,proto3,oneof"`
}

func (*GenerateRequest_SchemaId) isGenerateRequest_Source() {}

func (*GenerateRequest_InlineSchema) isGenerateRequest_Source() {}

// Schema represents the blueprint of the dataset to be generated.
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for the schema.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Ordered collection of fields that define the dataset structure.
	Fields        []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_api_proto_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Field represents a single column in the dataset.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the column (e.g., "id", "customer_name", "transaction_amount").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Identifier for the data provider/generator (e.g., "uuid", "int_range", "email").
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// List of configuration parameters for the provider.
	Options       []*Option `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_api_proto_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Field) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// Option provides type-safe configuration for field providers.
// This design avoids runtime string parsing, optimizing CPU cycles.
type Option struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameter name (e.g., "min", "max", "format", "distribution").
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Type-specific value for the option.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Option_StringVal
	//	*Option_IntVal
	//	*Option_FloatVal
	//	*Option_BoolVal
	Value         isOption_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_api_proto_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_proto_rawDescGZIP(), []int{3}
}

func (x *Option) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Option) GetValue() isOption_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Option) GetStringVal() string {
	if x != nil {
		if x, ok := x.Value.(*Option_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *Option) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*Option_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *Option) GetFloatVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*Option_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

func (x *Option) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*Option_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

type isOption_Value interface {
	isOption_Value()
}

type Option_StringVal struct {
	StringVal string `protobuf:"bytes,2,opt,name=string_val,json=stringVal,proto3,oneof"` // For patterns, formats, or categories.
}

type Option_IntVal struct {
	IntVal int64 `protobuf:"varint,3,opt,name=int_val,json=intVal,proto3,oneof"` // For discrete bounds and counts.
}

type Option_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,4,opt,name=float_val,json=floatVal,proto3,oneof"` // For continuous bounds and weights.
}

type Option_BoolVal struct {
	BoolVal bool `protobuf:"varint,5,opt,name=bool_val,json=boolVal,proto3,oneof"` // For toggleable features (e.g., "nullable").
}

func (*Option_StringVal) isOption_Value() {}

func (*Option_IntVal) isOption_Value() {}

func (*Option_FloatVal) isOption_Value() {}

func (*Option_BoolVal) isOption_Value() {}

// GeneratedRecord represents a single row of generated data.
type GeneratedRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered list of values corresponding to the schema fields.
	// Values are converted to string for transport but follow the schema order.
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedRecord) Reset() {
	*x = GeneratedRecord{}
	mi := &file_api_proto_generator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedRecord) ProtoMessage() {}

func (x *GeneratedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedRecord.ProtoReflect.Descriptor instead.
func (*GeneratedRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_proto_rawDescGZIP(), []int{4}
}

func (x *GeneratedRecord) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_api_proto_generator_proto protoreflect.FileDescriptor

const file_api_proto_generator_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/generator.proto\x12\fgenerator.v1\"\xa1\x01\n" +
	"\x0fGenerateRequest\x12\x1d\n" +
	"\tschema_id\x18\x01 \x01(\tH\x00R\bschemaId\x12;\n" +
	"\rinline_schema\x18\x02 \x01(\v2\x14.generator.v1.SchemaH\x00R\finlineSchema\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\rR\x04seedB\b\n" +
	"\x06source\"I\n" +
	"\x06Schema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06fields\x18\x02 \x03(\v2\x13.generator.v1.FieldR\x06fields\"g\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12.\n" +
	"\aoptions\x18\x03 \x03(\v2\x14.generator.v1.OptionR\aoptions\"\x9b\x01\n" +
	"\x06Option\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\n" +
	"string_val\x18\x02 \x01(\tH\x00R\tstringVal\x12\x19\n" +
	"\aint_val\x18\x03 \x01(\x03H\x00R\x06intVal\x12\x1d\n" +
	"\tfloat_val\x18\x04 \x01(\x01H\x00R\bfloatVal\x12\x1b\n" +
	"\bbool_val\x18\x05 \x01(\bH\x00R\aboolValB\a\n" +
	"\x05value\")\n" +
	"\x0fGeneratedRecord\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2d\n" +
	"\x10GeneratorService\x12P\n" +
	"\x0eStreamGenerate\x12\x1d.generator.v1.GenerateRequest\x1a\x1d.generator.v1.GeneratedRecord0\x01B6Z4github.com/aapldev00/synthetic_gen_gaas/pkg/genprotob\x06proto3"

var (
	file_api_proto_generator_proto_rawDescOnce sync.Once
	file_api_proto_generator_proto_rawDescData []byte
)

func file_api_proto_generator_proto_rawDescGZIP() []byte {
	file_api_proto_generator_proto_rawDescOnce.Do(func() {
		file_api_proto_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_generator_proto_rawDesc), len(file_api_proto_generator_proto_rawDesc)))
	})
	return file_api_proto_generator_proto_rawDescData
}

var file_api_proto_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_generator_proto_goTypes = []any{
	(*GenerateRequest)(nil), // 0: generator.v1.GenerateRequest
	(*Schema)(nil),          // 1: generator.v1.Schema
	(*Field)(nil),           // 2: generator.v1.Field
	(*Option)(nil),          // 3: generator.v1.Option
	(*GeneratedRecord)(nil), // 4: generator.v1.GeneratedRecord
}
var file_api_proto_generator_proto_depIdxs = []int32{
	1, // 0: generator.v1.GenerateRequest.inline_schema:type_name -> generator.v1.Schema
	2, // 1: generator.v1.Schema.fields:type_name -> generator.v1.Field
	3, // 2: generator.v1.Field.options:type_name -> generator.v1.Option
	0, // 3: generator.v1.GeneratorService.StreamGenerate:input_type -> generator.v1.GenerateRequest
	4, // 4: generator.v1.GeneratorService.StreamGenerate:output_type -> generator.v1.GeneratedRecord
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_generator_proto_init() }
func file_api_proto_generator_proto_init() {
	if File_api_proto_generator_proto != nil {
		return
	}
	file_api_proto_generator_proto_msgTypes[0].OneofWrappers = []any{
		(*GenerateRequest_SchemaId)(nil),
		(*GenerateRequest_InlineSchema)(nil),
	}
	file_api_proto_generator_proto_msgTypes[3].OneofWrappers = []any{
		(*Option_StringVal)(nil),
		(*Option_IntVal)(nil),
		(*Option_FloatVal)(nil),
		(*Option_BoolVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_generator_proto_rawDesc), len(file_api_proto_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_generator_proto_goTypes,
		DependencyIndexes: file_api_proto_generator_proto_depIdxs,
		MessageInfos:      file_api_proto_generator_proto_msgTypes,
	}.Build()
	File_api_proto_generator_proto = out.File
	file_api_proto_generator_proto_goTypes = nil
	file_api_proto_generator_proto_depIdxs = nil
}
