// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/generator.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeneratorService_StreamGenerate_FullMethodName = "/generator.v1.GeneratorService/StreamGenerate"
)

// GeneratorServiceClient is the client API for GeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GeneratorService defines the capabilities for synthetic data orchestration.
type GeneratorServiceClient interface {
	// StreamGenerate initiates a server-side streaming connection.
	// The server will push generated records as they are produced until
	// the requested count is reached or the context is cancelled.
	StreamGenerate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GeneratedRecord], error)
}

type generatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratorServiceClient(cc grpc.ClientConnInterface) GeneratorServiceClient {
	return &generatorServiceClient{cc}
}

func (c *generatorServiceClient) StreamGenerate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GeneratedRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GeneratorService_ServiceDesc.Streams[0], GeneratorService_StreamGenerate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GeneratedRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeneratorService_StreamGenerateClient = grpc.ServerStreamingClient[GeneratedRecord]

// GeneratorServiceServer is the server API for GeneratorService service.
// All implementations must embed UnimplementedGeneratorServiceServer
// for forward compatibility.
//
// GeneratorService defines the capabilities for synthetic data orchestration.
type GeneratorServiceServer interface {
	// StreamGenerate initiates a server-side streaming connection.
	// The server will push generated records as they are produced until
	// the requested count is reached or the context is cancelled.
	StreamGenerate(*GenerateRequest, grpc.ServerStreamingServer[GeneratedRecord]) error
	mustEmbedUnimplementedGeneratorServiceServer()
}

// UnimplementedGeneratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeneratorServiceServer struct{}

func (UnimplementedGeneratorServiceServer) StreamGenerate(*GenerateRequest, grpc.ServerStreamingServer[GeneratedRecord]) error {
	return status.Error(codes.Unimplemented, "method StreamGenerate not implemented")
}
func (UnimplementedGeneratorServiceServer) mustEmbedUnimplementedGeneratorServiceServer() {}
func (UnimplementedGeneratorServiceServer) testEmbeddedByValue()                          {}

// UnsafeGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratorServiceServer will
// result in compilation errors.
type UnsafeGeneratorServiceServer interface {
	mustEmbedUnimplementedGeneratorServiceServer()
}

func RegisterGeneratorServiceServer(s grpc.ServiceRegistrar, srv GeneratorServiceServer) {
	// If the following call panics, it indicates UnimplementedGeneratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeneratorService_ServiceDesc, srv)
}

func _GeneratorService_StreamGenerate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeneratorServiceServer).StreamGenerate(m, &grpc.GenericServerStream[GenerateRequest, GeneratedRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeneratorService_StreamGenerateServer = grpc.ServerStreamingServer[GeneratedRecord]

// GeneratorService_ServiceDesc is the grpc.ServiceDesc for GeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "generator.v1.GeneratorService",
	HandlerType: (*GeneratorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGenerate",
			Handler:       _GeneratorService_StreamGenerate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/generator.proto",
}
